// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Scoreboard struct {
	ID        uuid.UUID `json:"id"`
	Results   string    `json:"results"`
	Player    int32     `json:"player"`
	Computer  int32     `json:"computer"`
	CreatedAt time.Time `json:"created_at"`
}
